"use client";

import Fact from "@/components/Fact";
import "./page.scss";
import styles from "./intro.module.scss";

// pages/_app.js
import { Lato } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const lato = Lato({
	subsets: ["latin"],
	weight: ["400", "700"],
});

const facts: Fact[] = [
	{
		background: {
			color: "rgb(224, 65, 65)",
		},
		icon: "/images/icons/players.svg",
		intro: "Revenue Generated By ESports Worldwide",
		source: {
			name: "CNN",
			url: "http://edition.cnn.com/2016/05/31/sport/esports-is-professional-gaming-a-sport/",
		},
		increment: {
			value: 283.5,
			unit: "£",
		},
	},
	{
		background: {
			color: "rgb(0, 140, 221)",
		},
		icon: (
			<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
				<title>PlayStation</title>
				<path
					d="M8.984 2.596v17.547l3.915 1.261V6.688c0-.69.304-1.151.794-.991.636.18.76.814.76 1.505v5.875c2.441 1.193 4.362-.002 4.362-3.152 0-3.237-1.126-4.675-4.438-5.827-1.307-.448-3.728-1.186-5.39-1.502zm4.656 16.241l6.296-2.275c.715-.258.826-.625.246-.818-.586-.192-1.637-.139-2.357.123l-4.205 1.5V14.98l.24-.085s1.201-.42 2.913-.615c1.696-.18 3.785.03 5.437.661 1.848.601 2.04 1.472 1.576 2.072-.465.6-1.622 1.036-1.622 1.036l-8.544 3.107V18.86zM1.807 18.6c-1.9-.545-2.214-1.668-1.352-2.32.801-.586 2.16-1.052 2.16-1.052l5.615-2.013v2.313L4.205 17c-.705.271-.825.632-.239.826.586.195 1.637.15 2.343-.12L8.247 17v2.074c-.12.03-.256.044-.39.073-1.939.331-3.996.196-6.038-.479z"
					fill="white"
				/>
			</svg>
		),
		intro: "Spent On Gaming Consoles In Western Europe",
		source: {
			name: "Statista",
			url: "https://www.statista.com/statistics/260172/gaming-console-revenue-in-western-europe/",
		},
		increment: {
			value: 278,
			unit: "£",
		},
	},
	{
		background: {
			color: "#6441a5",
		},
		icon: (
			<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
				<title>Twitch</title>
				<path
					d="M11.571 4.714h1.715v5.143H11.57zm4.715 0H18v5.143h-1.714zM6 0L1.714 4.286v15.428h5.143V24l4.286-4.286h3.428L22.286 12V0zm14.571 11.143l-3.428 3.428h-3.429l-3 3v-3H6.857V1.714h13.714Z"
					fill="white"
				/>
			</svg>
		),
		intro: "Watched on Twitch",
		source: {
			name: "Twitch 2015 Retrospective",
			url: "https://www.twitch.tv/year/2015",
		},
		increment: {
			value: 127.5,
			unit: "Hours",
		},
	},
	{
		background: {
			color: "#000000",
		},
		icon: (
			<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
				<title>Steam</title>
				<path
					d="M11.979 0C5.678 0 .511 4.86.022 11.037l6.432 2.658c.545-.371 1.203-.59 1.912-.59.063 0 .125.004.188.006l2.861-4.142V8.91c0-2.495 2.028-4.524 4.524-4.524 2.494 0 4.524 2.031 4.524 4.527s-2.03 4.525-4.524 4.525h-.105l-4.076 2.911c0 .052.004.105.004.159 0 1.875-1.515 3.396-3.39 3.396-1.635 0-3.016-1.173-3.331-2.727L.436 15.27C1.862 20.307 6.486 24 11.979 24c6.627 0 11.999-5.373 11.999-12S18.605 0 11.979 0zM7.54 18.21l-1.473-.61c.262.543.714.999 1.314 1.25 1.297.539 2.793-.076 3.332-1.375.263-.63.264-1.319.005-1.949s-.75-1.121-1.377-1.383c-.624-.26-1.29-.249-1.878-.03l1.523.63c.956.4 1.409 1.5 1.009 2.455-.397.957-1.497 1.41-2.454 1.012H7.54zm11.415-9.303c0-1.662-1.353-3.015-3.015-3.015-1.665 0-3.015 1.353-3.015 3.015 0 1.665 1.35 3.015 3.015 3.015 1.663 0 3.015-1.35 3.015-3.015zm-5.273-.005c0-1.252 1.013-2.266 2.265-2.266 1.249 0 2.266 1.014 2.266 2.266 0 1.251-1.017 2.265-2.266 2.265-1.253 0-2.265-1.014-2.265-2.265z"
					fill="white"
				/>
			</svg>
		),
		intro: "Spent On Steam Games Worldwide",
		source: {
			name: "gamesindustry.biz",
			url: "http://www.gamesindustry.biz/articles/2017-01-06-steam-paid-game-revenue-flat-in-2016-despite-escalating-releases-steam-spy",
		},
		increment: {
			value: 88,
			unit: "£",
		},
	},
	{
		background: {
			color: "#107c10",
		},
		intro: "Spent On Physical Games In The UK",
		source: {
			name: "gamesindustry.biz",
			url: "http://www.gamesindustry.biz/articles/2017-01-03-uk-physical-games-market-suffers-13-4-percent-drop-in-2016",
		},
		increment: {
			value: 0.75,
			unit: "£",
		},
	},
];

export default function Home() {
	return (
		<>
			<style jsx global>{`
				html {
					font-family: ${lato.style.fontFamily};
				}
			`}</style>
			<main className={styles.lato}>
				<section className={styles.intro}>
					<aside className={styles.credits}>
						<h2>Credits</h2>
						<a
							href="http://benmichaeljoy.com/"
							style={{
								color: "inherit",
								textDecoration: "none",
							}}
						>
							<div>
								<h3
									style={{
										display: "inline",
									}}
								>
									Ben Joy
								</h3>
								<h3
									style={{
										display: "inline",
										marginLeft: "10px",
										color: "rgba(15, 14, 17, .2)",
									}}
								>
									Beard Grower
								</h3>
							</div>
						</a>
						<a
							href="http://whatjackhasmade.co.uk/"
							style={{
								color: "inherit",
								textDecoration: "none",
							}}
						>
							<div>
								<h3
									style={{
										display: "inline",
									}}
								>
									Jack Davies
								</h3>
								<h3
									style={{
										display: "inline",
										marginLeft: "10px",
										color: "rgba(15, 14, 17, .2)",
									}}
								>
									Coffee Inhaler
								</h3>
							</div>
						</a>
					</aside>
					<h1
						style={{
							marginTop: "0",
						}}
					>
						Video Games in real time
					</h1>
					<p
						style={{
							fontWeight: "bold",
						}}
					>
						Scroll down to see what has happened in the video game world since
						you landed on this page!
					</p>
					<a href="#facts">
						<img
							class="max-width--50 animate animate--down"
							src="http://realtimegames.today/wp-content/uploads/2017/04/arrow.svg"
							alt="animated down arrow"
						/>
					</a>
				</section>
				{facts.map((fact) => (
					<Fact {...fact} key={`fact-${fact.intro}`} />
				))}
				<footer
					role="contentinfo"
					style={{
						textAlign: "center",
						padding: "20px",
						backgroundColor: "#14213d",
					}}
				>
					<p
						style={{
							margin: "0",
							color: "white",
						}}
					>
						© {new Date().getFullYear()} Copyright RealTimeGames.
					</p>
				</footer>
			</main>
		</>
	);
}
